export const strategyRouterAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "addressesProvider",
        type: "address",
        internalType: "address",
      },
      { name: "_factory", type: "address", internalType: "address" },
      {
        name: "dataProvider",
        type: "address",
        internalType: "address",
      },
      { name: "_swapRouter", type: "address", internalType: "address" },
      {
        name: "_positionManager",
        type: "address",
        internalType: "address",
      },
      { name: "_permit2", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DATA_PROVIDER",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IAaveProtocolDataProvider",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ORACLE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPriceOracleGetter",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PROVIDER",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPoolAddressesProvider",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "changeAdmin",
    inputs: [{ name: "newAdmin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closePosition",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collectFees",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "collected0", type: "uint256", internalType: "uint256" },
      { name: "collected1", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract AccountFactory",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUniswapV4PoolConfig",
    inputs: [],
    outputs: [
      { name: "token0", type: "address", internalType: "address" },
      { name: "token1", type: "address", internalType: "address" },
      { name: "fee", type: "uint24", internalType: "uint24" },
      { name: "tickSpacing", type: "int24", internalType: "int24" },
      {
        name: "defaultTickLower",
        type: "int24",
        internalType: "int24",
      },
      { name: "defaultTickUpper", type: "int24", internalType: "int24" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initPermit2",
    inputs: [
      { name: "token0", type: "address", internalType: "address" },
      { name: "token1", type: "address", internalType: "address" },
      { name: "poolManager", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "openPosition",
    inputs: [
      { name: "supplyAsset", type: "address", internalType: "address" },
      {
        name: "supplyAmount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "borrowAsset", type: "address", internalType: "address" },
      { name: "targetHF1e18", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "permit2",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IPermit2" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionManager",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPositionManager",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positions",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "vault", type: "address", internalType: "address" },
      { name: "supplyAsset", type: "address", internalType: "address" },
      { name: "borrowAsset", type: "address", internalType: "address" },
      { name: "isOpen", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewBorrow",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "supplyAsset", type: "address", internalType: "address" },
      {
        name: "supplyAmount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "borrowAsset", type: "address", internalType: "address" },
      { name: "targetHF1e18", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "finalToken", type: "uint256", internalType: "uint256" },
      {
        name: "projectedHF1e18",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "byHFToken", type: "uint256", internalType: "uint256" },
      {
        name: "policyMaxToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "capRemainingToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "liquidityToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "collBeforeBase",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "debtBeforeBase",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "collAfterBase",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "ltBeforeBps", type: "uint256", internalType: "uint256" },
      { name: "ltAfterBps", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewClosePosition",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "vault", type: "address", internalType: "address" },
      { name: "supplyAsset", type: "address", internalType: "address" },
      { name: "borrowAsset", type: "address", internalType: "address" },
      {
        name: "totalDebtToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lpBorrowTokenAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minExtraFromUser",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxExtraFromUser",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "amount0FromLp",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "amount1FromLp",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewLiquidity",
    inputs: [
      {
        name: "amount0ForLp",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "amount1ForLp", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewLpWithdrawAmounts",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "token0", type: "address", internalType: "address" },
      { name: "token1", type: "address", internalType: "address" },
      { name: "amount0", type: "uint256", internalType: "uint256" },
      { name: "amount1", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewUniPosition",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "token0", type: "address", internalType: "address" },
      { name: "token1", type: "address", internalType: "address" },
      { name: "liquidity", type: "uint128", internalType: "uint128" },
      { name: "amount0Now", type: "uint256", internalType: "uint256" },
      { name: "amount1Now", type: "uint256", internalType: "uint256" },
      { name: "tickLower", type: "int24", internalType: "int24" },
      { name: "tickUpper", type: "int24", internalType: "int24" },
      { name: "currentTick", type: "int24", internalType: "int24" },
      { name: "sqrtPriceX96", type: "uint160", internalType: "uint160" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "safe_borrow_bps",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setSafeBorrowBfs",
    inputs: [{ name: "newBps", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUniswapV4PoolConfig",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          {
            name: "currency0",
            type: "address",
            internalType: "Currency",
          },
          {
            name: "currency1",
            type: "address",
            internalType: "Currency",
          },
          { name: "fee", type: "uint24", internalType: "uint24" },
          { name: "tickSpacing", type: "int24", internalType: "int24" },
          {
            name: "hooks",
            type: "address",
            internalType: "contract IHooks",
          },
        ],
      },
      {
        name: "defaultTickLower",
        type: "int24",
        internalType: "int24",
      },
      { name: "defaultTickUpper", type: "int24", internalType: "int24" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "swapRouter",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract Miniv4SwapRouter",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userPositionIds",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AdminChanged",
    inputs: [
      {
        name: "previousAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeesCollected",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "token0",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "token1",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount0",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount1",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionClosed",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "vault",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "supplyAsset",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "borrowAsset",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amountSupplyReturned",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amountBorrowReturned",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionOpened",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "vault",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "supplyAsset",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "supplyAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "borrowAsset",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "borrowedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount0ForLp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount1ForLp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "spent0",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "spent1",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SafeBorrowBpsUpdated",
    inputs: [
      {
        name: "previousBps",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "newBps",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BorrowAmountZero", inputs: [] },
  { type: "error", name: "BorrowCapExceeded", inputs: [] },
  { type: "error", name: "BorrowingDisabled", inputs: [] },
  { type: "error", name: "InsufficientLiquidity", inputs: [] },
  { type: "error", name: "InvalidBps", inputs: [] },
  { type: "error", name: "NotAdmin", inputs: [] },
  { type: "error", name: "NotEnoughToRepay", inputs: [] },
  { type: "error", name: "NotPositionOwner", inputs: [] },
  { type: "error", name: "OraclePriceZero", inputs: [] },
  { type: "error", name: "PositionNotOpen", inputs: [] },
  { type: "error", name: "SameAddress", inputs: [] },
  { type: "error", name: "SameValue", inputs: [] },
  { type: "error", name: "SupplyingDisabled", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "TransferFromFailed", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "ZeroBorrowAfterSafety", inputs: [] },
] as const;
